### ISSUE TITLE
Calling Session.verifySession middleware in a different file throws error

### ISSUE THREAD

**Issue by ankitjena** [supertokens/supertokens-node#122]
## Description
When I try to apply the verifySession middleware in a different file(separate router instance which I apply to my app after supertokens initialisation)
```
import Session from 'supertokens-node/recipe/session';
import express from 'express';
import { getUser } from '../../controllers/v1/user';

const router = express.Router();

router.get('/me', Session.verifySession(), getUser);

export default router;

```

 I get the following error
```
SessionError {
  getRecipeId: [Function],
  type: 'GENERAL_ERROR',
  message: 'Initialisation not done. Did you forget to call the SuperTokens.init function?',
  payload: Error: Initialisation not done. Did you forget to call the SuperTokens.init function?
      at Function.getInstanceOrThrowError (/home/ankitjey/Desktop/sideprojects/unnamed-backend/node_modules/supertokens-node/lib/build/recipe/session/sessionRecipe.js:318:26)
      at Function.SessionWrapper.verifySession (/home/ankitjey/Desktop/sideprojects/unnamed-backend/node_modules/supertokens-node/lib/build/recipe/session/index.js:60:63)
      at Object.<anonymous> (/home/ankitjey/Desktop/sideprojects/unnamed-backend/src/routes/v1/user.ts:7:27)
      at Module._compile (internal/modules/cjs/loader.js:1137:30)
      at Module.m._compile (/home/ankitjey/Desktop/sideprojects/unnamed-backend/node_modules/ts-node/src/index.ts:858:23)
      at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
      at Object.require.extensions.<computed> [as .ts] (/home/ankitjey/Desktop/sideprojects/unnamed-backend/node_modules/ts-node/src/index.ts:861:12)
      at Module.load (internal/modules/cjs/loader.js:985:32)
      at Function.Module._load (internal/modules/cjs/loader.js:878:14)
      at Module.require (internal/modules/cjs/loader.js:1025:19)
      at require (internal/modules/cjs/helpers.js:72:18)
      at Object.<anonymous> (/home/ankitjey/Desktop/sideprojects/unnamed-backend/src/index.ts:21:1)
      at Module._compile (internal/modules/cjs/loader.js:1137:30)
      at Module.m._compile (/home/ankitjey/Desktop/sideprojects/unnamed-backend/node_modules/ts-node/src/index.ts:858:23)
      at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
      at Object.require.extensions.<computed> [as .ts] (/home/ankitjey/Desktop/sideprojects/unnamed-backend/node_modules/ts-node/src/index.ts:861:12),
  recipe: undefined,
  errMagic: 'ndskajfasndlfkj435234krjdsa'
}
```
Using the cerifySession middleware on the app.use call where I use the separate router works fine
```
app.use('/api/user', Session.verifySession(), userRouter);
```

**Comment by rishabhpoddar** [comment]
For versions older than 5.0.1, this issue can be fixed by:
- Using `(req, res, next) => Session.verifySession()(req, res, next)` instead of `Session.verifySession()`
- Using `app.use((req, res, next) => supertokens.middleware()(req, res, next))` instead of `app.use(supertokens.middleware())
- Using `app.use((req, res, next) => supertokens.errorHandler()(req, res, next))` instead of `app.use(supertokens.errorHandler())
