### ISSUE TITLE
Incorrect Response code

### ISSUE THREAD

**Issue by rajivharlalka** [supertokens/supertokens-node#270]
When using passwordless recipie, if GET requests are made instead of POST for api calls on postman, an error
```
TypeError: Cannot read properties of undefined (reading 'returnAPIIdIfCanHandleRequest')
    at SuperTokens.<anonymous> (/home/vijard/Documents/projects/mello/griffin/node_modules/supertokens-node/lib/build/supertokens.js:198:56)
    at Generator.next (<anonymous>)
    at /home/vijard/Documents/projects/mello/griffin/node_modules/supertokens-node/lib/build/supertokens.js:44:75
    at new Promise (<anonymous>)
    at __awaiter (/home/vijard/Documents/projects/mello/griffin/node_modules/supertokens-node/lib/build/supertokens.js:26:16)
    at SuperTokens.middleware (/home/vijard/Documents/projects/mello/griffin/node_modules/supertokens-node/lib/build/supertokens.js:157:13)
    at /home/vijard/Documents/projects/mello/griffin/node_modules/supertokens-node/lib/build/framework/express/framework.js:153:50
    at Generator.next (<anonymous>)
    at /home/vijard/Documents/projects/mello/griffin/node_modules/supertokens-node/lib/build/framework/express/framework.js:44:75
    at new Promise (<anonymous>)
```

gets thrown instead of a generic 404.

SuperTokens-node version: 8.6.0
nodejs version: 16.13.2
OS: Arch Linux ; kernel 5.15.24-1-lts

**Comment by bhumilsarvaiya** [comment]
Hey @rajivharlalka , can you share your server code snippet where you are calling supertokens.init function?

**Comment by rajivharlalka** [comment]
Here's the code snippet for the init function

```javascript
const initSupertokens = () => {
    supertokens.init({
        framework: "express",
        supertokens: {
            // These are the connection details of the app you created on supertokens.io
            connectionURI: config.supertokens.url,
            apiKey: config.supertokens.api_key,
        },
        appInfo: {
            // learn more about this on https://supertokens.io/docs/session/appinfo
            appName: "griffin",
            apiDomain: config.urls.backend,
            websiteDomain: config.urls.frontend,
            apiBasePath: "/api/auth",
            websiteBasePath: "/auth",
        },
        recipeList: [
            Passwordless.init({
                flowType: "USER_INPUT_CODE",
                contactMethod: "EMAIL_OR_PHONE",
                createAndSendCustomEmail: async function (input) {
                    sendEmailOtp(input.email, input.userInputCode);
                },
                createAndSendCustomTextMessage: async (input, context) => {
                    /* See next step */
                },
            }),
            ,
            Session.init(),
        ],
    });
    Logger.info("Supertokens connected.");
};

```

**Comment by bhumilsarvaiya** [comment]
![Screenshot 2022-03-01 at 1 40 19 PM](https://user-images.githubusercontent.com/21988812/156130389-1204ef26-af40-476e-b070-2be5bddd92ed.png)

Hey, please remove the extra `,` and try again

**Comment by rajivharlalka** [comment]
That worked 😅 , Thanks . Though why did that comma have such a effect .

**Comment by bhumilsarvaiya** [comment]
It added an empty item in the array. So, in the array which should only have items of type `RecipeModule`, there was an empty item also.

**Comment by rajivharlalka** [comment]
Closed by mistake, sorry !

**Comment by rishabhpoddar** [comment]
In v9.0.1, we now throw an error in case an empty item is passed in the recipe list
