### ISSUE TITLE
Error thrown after importing `emailpassword` recipe (supertokens-node v13)

### ISSUE THREAD

**Issue by markmanx** [supertokens/supertokens-node#513]
Node version: 19.7.0
Package: supertokens-node v13.1.3

Error can be reproduced using a minimal setup (simply import from `supertokens-node/recipe/thirdpartyemailpassword`).
Note: Doesn't seem to be an issue in v12.

package.json:
```
{
  "name": "supertokens-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node server.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "supertokens-node": "^13.1.3"
  }
}
```

server.js
```
const ThirdPartyEmailPassword = require("supertokens-node/recipe/thirdpartyemailpassword");
```

Error thrown:
```
/Users/markmankarious/Projects/supertokens-test/node_modules/supertokens-node/lib/build/recipe/emailpassword/index.js:111
Wrapper.init = recipe_1.default.init;
                                ^

TypeError: Cannot read properties of undefined (reading 'init')
    at Object.<anonymous> (/Users/markmankarious/Projects/supertokens-test/node_modules/supertokens-node/lib/build/recipe/emailpassword/index.js:111:33)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (/Users/markmankarious/Projects/supertokens-test/node_modules/supertokens-node/lib/build/recipe/dashboard/utils.js:60:41)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    ```

**Comment by rishabhpoddar** [comment]
This has been fixed in node sdk version >= 13.1.4
